### ISSUE TITLE
Potential Performance Improvement in Nuclei Detection

### ISSUE THREAD

**Issue by william-silversmith** [htem/FANC_auto_recon#11]
Hi FANC people,

I was looking over some repos that are using cc3d and I saw that you may potentially benefit substantively from some more recent functions introduced into cc3d in the nucleus detector, specifically around the bbox calculations.

https://github.com/htem/FANC_auto_recon/blob/d05a4ad1a865e3347368074914ccbde914b0dd94/nuclei_prediction/get_nuc.py#L147-L153

This code requires repeated calculation on the image and has bilinear performance. You can get the same result much faster by using `cc3d.statistics`

```python
cc_out, N = cc3d.connected_components(masked, return_N=True, connectivity=connectivity)
stats = cc3d.statistics(cc_out) # calculates centroids, bboxes, and volume in one pass
bboxes = stats["bounding_boxes"]  # ndarray, index is CCL ID
centroids = stats["centroids"] # ndarray, index is CCL ID
```

Not sure if this will materially help your project, but I figure it wouldn't hurt if you happen to run this task more than once.

Will

**Comment by sumiya-kuroda** [comment]
Hello Will. Thank you so much for your feedback. It seems your `cc3d.statistics` can significantly improve the nucelus detecting process. While there is no plan to run this code again, I will update the code to make it more efficient.

**Comment by william-silversmith** [comment]
Hope it helps! Even if only as a template for similar activities.
