### ISSUE TITLE
Render a more feature-rich neuroglancer scene programmatically

### ISSUE THREAD

**Issue by jasper-tms** [htem/FANC_auto_recon#2]
It'd be nice to be able to programmatically generate a feature-rich neuroglancer scene that can act as "home base" for then programmatically adding stuff on top of it like (1) annotation layers or (2) selecting certain segments based on skeletons. Specific things that are in the link currently pinned to #proofreading-access that would be nice to have programmatically include

- [x] Image layer named `FANCv4`
- [x] Proofreading layer named `seg_Mar2021_proofreading`
- [x] Layer with the volume outlines named `volume outlines`
- [x] GPU memory limit ~4GB
- [x] System memory limit ~4GB
- [x] Concurrent chunk requests 64

**Comment by jasper-tms** [comment]
I see from one of @sumiya-kuroda 's notebooks that this kind of thing will do the trick:

```
imgTokyo = ImageLayerConfig(name = 'FANCv4-jp',
                                    source = auth.get_cv_path('Image_Tokyo')['url'])
img = ImageLayerConfig(name = 'FANCv4',
                                    source = auth.get_cv_path('Image')['url'])
seg = SegmentationLayerConfig(name = 'seg_Mar2021_proofreading',
                                    source = auth.get_cv_path('FANC_production_segmentation')['url'])     

memory_options = {"gpuMemoryLimit": 4000000000,
                  "systemMemoryLimit": 8000000000,
                  "concurrentDownloads": 64,
                  "jsonStateServer": "https://global.daf-apis.com/nglstate/api/v1/post"}

nuc = SegmentationLayerConfig(name = 'neuron_nuclei_Aug2021',
                                        active = True,
                                        source = auth.get_cv_path('nuclei_seg_Aug2021')['url'],
                                        selected_ids_column='nucID')             
                                                            
sb = StateBuilder(layers=[imgTokyo, seg, nuc, img],resolution=[4.3,4.3,45]) # view_kws=view_options
state = json.loads(sb.render_state(dftmp, return_as='json'))
state.update(memory_options)
jsn_id = client.state.upload_state_json(state)
output = client.state.build_neuroglancer_url(jsn_id, auth.get_cv_path('neuroglancer_base')['url'])
```

**Comment by sumiya-kuroda** [comment]
I added options to edit GPU memory limit, system memory limit, concurrent chunk requests, and background color in `proofreading/proofreading_utils.py/render_scene()` #15
