### ISSUE TITLE
Neuropil identification for all somas

### ISSUE THREAD

**Issue by sibocw** [htem/FANC_auto_recon#25]
Similar to #22 I also want to identify which neuropil each soma is in. I noticed that there's a new December soma table. @jasper-tms can you explain this to me before I start? We can chat on Friday when you're back.

**Comment by jasper-tms** [comment]
Info about the new soma tables: https://fanc-reconstruction.slack.com/archives/CLE1R5048/p1671568387097929

Somas aren't in neuropils, they instead sit just outside the neuropil. The outer edges of the VNC neuropil are defined by where there's a sharp transition between high density of synapses (neuropil) to low density of synapses (soma region). So I don't really think there's a useful way to classify somas into neuropils. The most sensible first order spatial classification for somas would be their hemilineage, I think.

**Comment by sibocw** [comment]
Thanks! Got it. Closing then.
