### ISSUE TITLE
Remove invalid (false positive) nucleus IDs from the nucleus segmentation

### ISSUE THREAD

**Issue by jasper-tms** [htem/FANC_auto_recon#27]
I want to be able to see all the nuclei that are in the CAVE table, as a layer in neuroglancer. To accomplish this I will make a new nucleus segmentation cloudvolume that contains only the manually verified nucleus IDs.

Source:`gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022`
Output: `gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022_verified`

I wrote some code to do this and ran it for a small fraction of the dataset, and it was immediately clear that this is going to be useful – it's very easy to spot the small % of nuclei that don't have a rainbow colored blob on them, and indeed those nuclei don't appear in the soma table, and so should be added. I'll get this finished up soon.

**Comment by jasper-tms** [comment]
My intention is to soon add a layer showing `nuclei_seg_Mar2022_verified` to the default neuroglancer state, since I think this will allow us to pretty quickly find most of the remaining nuclei in the dataset that are missing from the current table. Ideally, as we add new somas to the soma table, we would also update this layer so that new nuclei objects appear corresponding to the newly added nuclei. @sumiya-kuroda what do you think about the idea that when we add new nuclei to the soma table, we use a real ID of an object from the nucleus segmentation instead of an ID that starts with 1000000... . If we do this, we can also copy this new ID from `nuclei_seg_Mar2022` to `nuclei_seg_Mar2022_verified` as part of the function that adds a new soma to the CAVE table. This way the `_verified` layer will slowly grow to eventually have a nucleus segID for every nucleus.

**Comment by jasper-tms** [comment]
Here's the script I ran
```python
#!/usr/bin/env python3
"""
Strip the nucleus segmentation down to only the IDs that were manually
verified as true positives.
"""

from cloudvolume import CloudVolume

import fanc


# Open cloudvolumes
seg_input = CloudVolume('gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022')
seg_input.provenance.owners = ['Ran Lu <ranl@zetta.ai>',
                               'Sumiya Kuroda <sumiya.kuroda@gmail.com>',
                               'Jasper Phelps <jasper.s.phelps@gmail.com>',
                               'Wei-Chung Lee <wei-chung_lee@hms.harvard.edu>']
seg_input.provenance.description = (
    'Segmentation of nuclei from FANCv4. Nuclei were detected by a '
    'convolutional neural network trained and deployed by Ran Lu at Zetta AI. '
    'All predictions of the network are present in this volume, including many '
    'false positives (mostly small objects, though some large ones). For a set '
    'of predictions where all false positives have been removed by a '
    'combination of thresholding and manual inspection, see '
    'gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022_verified'
)
seg_input.commit_provenance()

seg_output = CloudVolume('gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022_verified',
                         info=seg_input.info)
seg_output.commit_info()
seg_output.provenance.owners = ['Sumiya Kuroda <sumiya.kuroda@gmail.com>',
                                'Ran Lu <ranl@zetta.ai>',
                                'Jasper Phelps <jasper.s.phelps@gmail.com>',
                                'Wei-Chung Lee <wei-chung_lee@hms.harvard.edu>']
seg_output.provenance.description = (
    'Segmentation of nuclei from FANCv4. Nuclei were detected by a '
    'convolutional neural network trained and deployed by Ran Lu at Zetta AI. '
    'All false positive nuclei predictions were then removed by a combination '
    'of applying thresholds and manual inspection. For the complete set of '
    'nuclei predictions (without removal of false positives), see '
    'gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022'
)
seg_output.commit_provenance()


# Pull list of verified nucleus IDs
client = fanc.get_caveclient()
somas = client.materialize.query_table('somas_dec2022')
verified_ids = set(somas.loc[somas.id > 20000000000000000, 'id'])
verified_ids.add(0)

def remove_invalid_ids_from_range(x_slice, y_slice, z_slice,
                                  valid_ids=verified_ids,
                                  verbose=False):
    """
    Process a given range of the nuclei predictions, removing invalid ids
    from seg_input and saving the result to the same location within seg_output.

    The default chunk_size and offset come from seg_input.info and shouldn't
    need to be changed.
    """
    if not isinstance(valid_ids, set):
        raise TypeError('valid_ids must be a set but was {}'.format(type(valid_ids)))

    data = np.array(seg_input[x_slice, y_slice, z_slice])

    if verbose: print('Running ravel & unique')
    unique_values = pd.unique(data.ravel())
    if verbose: print('Checking ids for validity')
    invalid_values = [i for i in unique_values if i not in valid_ids]
    if verbose: print('Removing invalid ids from data')
    data[np.isin(data, invalid_values)] = 0

    # Upload result
    seg_output[x_slice, y_slice, z_slice] = data


chunk_size = np.array((256, 256, 64))
offset = np.array((0, 0, 10))
for z in range(68):  # seg_input.shape[2]/seg_input.chunk_size[2] = 4390/64 = 68.6
    for y in range(55):  # seg_input.shape[1]/seg_input.chunk_size[1] = 14111/256 = 55.1
        print(f'z {z}/67 : y {y}/54')
        start_coord = chunk_size * (0, y, z) + offset
        remove_invalid_ids_from_range(
            slice(None), #slice(start_coord[0], start_coord[0]+chunk_size[0]),
            slice(start_coord[1], start_coord[1]+chunk_size[1]),
            slice(start_coord[2], start_coord[2]+chunk_size[2])
        )
# Handle the last rows/slices
for y in range(55):
    remove_invalid_ids_from_range(slice(None), slice(256*y, 256*(y+1)), slice(4362, 4400))
for z in range(68):
    remove_invalid_ids_from_range(slice(None), slice(14080, 14111), slice(z*64 + 10, (z+1)*64 + 10))
remove_invalid_ids_from_range(slice(None), slice(14080, 14111), slice(4362, 4400))
```

**Comment by jasper-tms** [comment]
Here's a [neuroglancer link](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/5177390535802880) showing the new verified nuclei segmentation layer. (The full nuclei segmentation is also in this neuroglancer state, as a hidden layer that you can show if you want to compare to the verified layer.)

**Comment by jasper-tms** [comment]
Oh, I should also copy the nucleus meshes for 3d visualization. I can copy all of them (no need to restrict to only copying the valid IDs – the meshes for invalid IDs will never get loaded, but it won't break anything). Running this:
> gsutil -m rsync -r gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022/mesh_mip_0/ gs://lee-lab_female-adult-nerve-cord/alignmentV4/nuclei/nuclei_seg_Mar2022_verified/mesh_mip_0/

This will take about an hour to complete. By the time any of you are reading this, you can assume this command has finished.

**Comment by sumiya-kuroda** [comment]
Thank you! I think this is a great idea to find missing nuclei. 

I'm just curious, but for all the manually identified nuclei already uploaded to the CAVE table so far, did you find any nuclei that are not detected in `nuclei_seg_Mar2022` at all?

**Comment by jasper-tms** [comment]
That's a great question that I haven't had time to look closely at yet. I would not be surprised if some small % of nuclei don't have even a small object in the nucleus segmentation that we could use for that nucleus, but I would be surprised if a significant % don't have any object. Even for nuclei that don't have any object, we could in principle manually write whatever values we want into the `nuclei_seg_Mar2022_verified` layer, for instance draw a cube filled with the value 10000000000XX into the middle of a nucleus that didn't originally have any object in the nucleus segmentation.
