### ISSUE TITLE
Write `get_anchor_point`

### ISSUE THREAD

**Issue by jasper-tms** [htem/FANC_auto_recon#30]
Given a segID, there are a few of ways to pick a point inside it that it "stable" and can be used as a reference point to anchor annotations and look up the new version of this segID if it gets proofread. I plan to write a function to makes this choice in a reliable way:
- For neurons with a soma, use the point in the soma table.
- For neurons with no soma but a point in a peripheral nerve, use the point in the peripheral nerve table
- For neurons with no soma and no point in the peripheral nerve table but a point in the neck connective table, use the point in the neck connective table.

I should make sure to check the results for neurons that are in multiple tables, e.g. motor neurons that have somas and a point in peripheral nerves, ascending interneurons that have somas and a point in the neck connective, and ascending sensory neurons that have a point in a peripheral nerve and the neck connective.

This will likely go in `fanc.lookup.get_anchor_point()`

**Comment by jasper-tms** [comment]
The function should raise errors with informative messages if no point is found or multiple points are found in a way that is unexpected, e.g. two soma points or multiple nerve points. (Note that some neurons do go out nerves multiple times, e.g. the DUM neurons, but these have somas so the soma point will just be used and the multiple nerve points won't cause an issue.)

**Comment by unidesigner** [comment]
Do I read this correctly that it implies that it does not make sense to define such a reference point for segments that have no point in any of the mentioned tables? That would also mean that a segment cannot be marked as proofread if it has no reference point according to your criteria?

**Comment by jasper-tms** [comment]
Yes, you're correct that that's what I was thinking. Can you think of situations where this wouldn't be a reasonable thing to enforce?

**Comment by unidesigner** [comment]
Ok. Just cases where for some reason (e.g. not properly predicted or missed in manual annotations) a point does not exist in any of those tables. But in this case it would be an interesting outlier and probably require the manual addition of a point in one of he tables, like you outline with the error message.

**Comment by jasper-tms** [comment]
Yes that's right. Adding points to the neck connective or peripheral nerve tables is very easy, and Sumiya wrote some code for adding missed somas to the soma table (which is a bit less trivial since there are more columns in that table). My plan of insisting that segIDs have an anchor point before they can be annotated does mean that I'm committing to be diligent about adding missing entries to those 3 anchor point tables as we identify points that should be added.

**Comment by unidesigner** [comment]
Sounds good. Better to enforce it as early as possible - saves time later.

**Comment by jasper-tms** [comment]
Implemented in 2cd22633e79fdf9208590f91d0c3d9290b171268
