### ISSUE TITLE
Keep track of `int() argument must be a string, a bytes like object or a number, not 'NoneType.'` error locations

### ISSUE THREAD

**Issue by jasper-tms** [htem/FANC_auto_recon#31]
A very small percent of the time when trying to do a merge operation, the chunkedgraph errors out and prints `int() argument must be a string, a bytes like object or a number, not 'NoneType.'` on the bottom bar of neuroglancer.

On April 4 2023 Casey said:
> Unfortunately that's a pychunkedgraph error right now that occurs in a small number of situations. We have a good sense of where the issue is (at long last), but have not yet had the chance to figure out a solution. The issue is usually related to highly fragmented neurites, so it's possible that the merge will work if you hop over the disconnected fragment and try to connect to the larger downstream yellow branch. Either way, I recommend noting this location and coming back to it once we report this error is fixed, whether to correct the topology of the merge if skipping the fragment works or to do the merge itself.

So here we are, a thread for keeping track of these instances.

- Andrew Cook reported "error when attempting to merge [this yellow branch to this red leg MN](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/5411048741928960)."
- I'm getting an error trying to merge a different small branch into the same motor neuron as in the instance above, [here](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/4909210334658560)

Folks in the community, please don't hesitate to to post more instances of this error here.

**Comment by jasper-tms** [comment]
Well that one motor neuron has so far been the root of all the problems I've seen. [Third instance of a failed merge with that motor neuron](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/4876955331592192)

**Comment by Andrewpcook** [comment]
[Here's another location on this motor neuron where I attempted to make a merge and got this error](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/5692364184092672)

**Comment by Andrewpcook** [comment]
[I came across another location on this motor neuron where I attempted to make a merge and got this error](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/5698612086439936)

**Comment by jasper-tms** [comment]
This bit of glia that someone probably accidentally merged into a neuron won't come off: [link](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/6237808714842112)

**Comment by jasper-tms** [comment]
I talked with Akhilesh about this and he says there's not a direct way to fix the currently broken objects in FANC, but that they're working on finishing up development of version 3 of the chunkedgraph. Subsequently migrating existing (v1 and v2) chunkedgraphs to v3 should result in these sorts of broken objects being fixed. v3 itself is almost ready, but the v2->v3 migration code isn't. Still, we can look forward to the possibility of these broken objects being fixed on the timescale of a few months, depending on how the v3 chunkedgraph stuff goes.

**Comment by jasper-tms** [comment]
This left side intersegmental neuron: https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/6618791490355200

**Comment by jasper-tms** [comment]
Closing this for now since there's nothing to be done. (We can still add neurons to this thread even after the issue is closed.) And we'll revisit these neurons one the new chunkedgraph is available and deployed for FANC to see if things are fixed.

**Comment by Andrewpcook** [comment]
[(Here's a small falsely merged segment that won't split)]

**Comment by Andrewpcook** [comment]
[Here's a small falsely merged segment that won't split.](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/6416573520674816)

**Comment by Andrewpcook** [comment]
[I get this error message when trying to make any edits to this T2L MN.](https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/4697633958395904)

**Comment by jasper-tms** [comment]
Another one, contributed by Alice Schildkamp: https://neuromancer-seung-import.appspot.com/?json_url=https://global.daf-apis.com/nglstate/api/v1/5060510200365056

**Comment by DanaSherman** [comment]
Encountered a similar problem with the Aedes dataset - couldn't perform a merge of these two neurons:
https://spelunker.cave-explorer.org/#!middleauth+https://global.daf-apis.com/nglstate/api/v1/5568143773663232
getting the following error: "int() argument must be a string, a bytes-like object or a real number, not 'NoneType'."
Is there any way to fix this? Thank you!

**Comment by jasper-tms** [comment]
Only asking Akhilesh/Zetta/Sven for an update about v3 chunkedgraph migration and hoping that they have something useful for you!

**Comment by aleyna-salem** [comment]
I came across this error in the Aedes dataset too, multiple merges weren't possible: 
https://spelunker.cave-explorer.org/#!middleauth+https://global.daf-apis.com/nglstate/api/v1/5387595584897024
