### ISSUE TITLE
Faster rootID lookups

### ISSUE THREAD

**Issue by jasper-tms** [htem/FANC_auto_recon#5]
[Our current method](https://github.com/htem/FANC_auto_recon/blob/c41584d2fbe0f795ace79a421899a7515e0beeb7/segmentation/rootID_lookup.py#L142) gets ~150 rootID lookups / second. Apparently Eric Perlman has some implementation that gets closer to ~1000 lookups / second, according to Greg. Let's figure out how to make that happen for us.

**Comment by jefferis** [comment]
@perlman can give more details, but I think the main points are 1) that he runs a service where the relevant data are local on fast disk 2) that he chunks by locality which you seem to be doing already 3) that the segmentation volume has been stored with a somewhat optimised format / chunk size for this kind of look up. You can see more at

* https://github.com/bocklab/transform_service
* https://github.com/flyconnectome/CloudVolumeServer (our previous version from @schlegelp)

Of course lookups / second are somewhat hard to compare across different datasets and the locality of the test data matters quite a bit.

**Comment by perlman** [comment]
I agree with @jefferis's enumeration.

Digging into (3), the FlyWire deformation fields we were given had 2D chunks.  Rechunking the data into cubes reduced the number of reads from disk.

I have a long deferred task to evaluate the performance of chunk size vs format {Zarr/zlib, Zarr/blosc, precomputed neuroglancer} vs library {cloud-volume, python-zarr, tensorstore}.

I am currently using ~8mb "cubes" (cube-like in physical units [nm]), zarr+blosc and tensorstore.

**Comment by jasper-tms** [comment]
@bjm5164 found some speedups (factor of 1.5 or 2ish) in af01a07be90c506384a671f87d5d86b986ae94d9 and 6e601aecb196a940e4554a43687ddd889e98d51f

**Comment by jasper-tms** [comment]
Thanks to @perlman for setting up this service!
https://github.com/htem/FANC_auto_recon/blob/main/transforms/realignment.py#L30
